// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5NZy3uBv2gqZsSJj-3zcQx_HEVzreWjo',
    appId: '1:500864820062:web:2c437a4bea2a0c01f8e5cf',
    messagingSenderId: '500864820062',
    projectId: 'portfolio-e97b1',
    authDomain: 'portfolio-e97b1.firebaseapp.com',
    storageBucket: 'portfolio-e97b1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5kvMjHdDirc6kZVNUWHgW8enc8i64vPY',
    appId: '1:500864820062:android:8e4b325a127e33d4f8e5cf',
    messagingSenderId: '500864820062',
    projectId: 'portfolio-e97b1',
    storageBucket: 'portfolio-e97b1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCj0zk4r8ttJLVVunw0SahVMiZ949mtC5s',
    appId: '1:500864820062:ios:6f21831d43a20df9f8e5cf',
    messagingSenderId: '500864820062',
    projectId: 'portfolio-e97b1',
    storageBucket: 'portfolio-e97b1.firebasestorage.app',
    iosBundleId: 'com.example.portfolioApp',
  );

}